### ISSUE TITLE
Bad Request Your request resulted in an error.

### ISSUE THREAD

**Issue by mcgeheran** [MGPelloni/cloudbeds#1]
When I try to configure the Cloudbed Wordpress plugin with my Client ID and Client Secret after clicking connect - I get a Bad Request - Your request resulted in an error dialog. 

![CB_WP_Error](https://github.com/MGPelloni/cloudbeds/assets/48894206/2d9edda1-b472-4455-ad2a-ba0f1014e25f)

**Comment by MGPelloni** [comment]
Thanks @mcgeheran, this was due to a error log bug and has been fixed in the latest version of the plugin. Let me know if the issue persists and I'll open the issue back up.
